### ISSUE TITLE
"tuple index out of range" error at startup

### ISSUE THREAD

**Issue by Underforest** [hifumibot/hifumibot#2]
When bot starts up, an error is sent. Maybe related to the game status changing. Reminder to devs: Check this issue and fix that, once done, close this issue.
```py
tuple index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "/usr/local/python/Hifumi-plus/shell/hifumi.py", line 82, in on_ready
    await self.change_presence(game=Game(name=g))
  File "/usr/local/lib/python3.6/site-packages/discord/client.py", line 1934, in change_presence
    yield from self.ws.change_presence(game=game, status=status, afk=afk)
  File "/usr/local/lib/python3.6/site-packages/discord/gateway.py", line 454, in change_presence
    yield from self.send(sent)
  File "/usr/local/lib/python3.6/site-packages/discord/gateway.py", line 419, in send
    yield from super().send(data)
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 309, in send
    yield from self.ensure_open()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 393, in ensure_open
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006, no reason.
```

**Comment by MaT1g3R** [comment]
Fml
