### ISSUE TITLE
imdb command TypeError

### ISSUE THREAD

**Issue by MaT1g3R** [hifumibot/hifumibot#22]
Triggered message: ~imdb Boko no pico
Traceback:
```py
Traceback (most recent call last):
  File "/root/venv/hifumi/lib/python3.6/site-packages/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/root/python_projects/Hifumi-plus/cogs/utilities.py", line 105, in imdb
    self.bot.localize(ctx)
  File "/root/python_projects/Hifumi-plus/core/utilities_core.py", line 54, in imdb
    eps = api.get_episodes(id_) if res.type == 'tv_series' else None
  File "/root/venv/hifumi/lib/python3.6/site-packages/imdbpie/imdbpie.py", line 230, in get_episodes
    for season in seasons:
TypeError: 'NoneType' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/python_projects/Hifumi-plus/bot/hifumi.py", line 161, in on_command_error
    res = command_error_handler(localize, exception)
  File "/root/python_projects/Hifumi-plus/bot/hifumi_functions.py", line 77, in command_error_handler
    raise exception
  File "/root/venv/hifumi/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "/root/venv/hifumi/lib/python3.6/site-packages/discord/ext/commands/core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/root/venv/hifumi/lib/python3.6/site-packages/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: 'NoneType' object is not iterable```

**Comment by Underforest** [comment]
> Boku no Pico
that pretty much explains everything

closing...

**Comment by Underforest** [comment]
jk
