### ISSUE TITLE
Exception MissingRequiredArgument raised while using "join" command without arguments

### ISSUE THREAD

**Issue by Underforest** [hifumibot/hifumibot#3]
**Issue**: Exception MissingRequiredArgument raised while using "join" command without arguments
**Error**: `Ignoring exception in on_command_error`; `discord.ext.commands.errors.MissingRequiredArgument: channel is a required argument that is missing`
**Traceback**:
The traceback is displayed as follows.
```py
Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "/usr/local/python/Hifumi-plus/bot/hifumi.py", line 108, in on_command_error
    self.get_language_dict(context), exception
  File "/usr/local/python/Hifumi-plus/scripts/discord_functions.py", line 49, in command_error_handler
    raise exception
  File "/usr/local/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 367, in invoke
    yield from self.prepare(ctx)
  File "/usr/local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 345, in prepare
    yield from self._parse_arguments(ctx)
  File "/usr/local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 313, in _parse_arguments
    kwargs[name] = yield from self.transform(ctx, param)
  File "/usr/local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 212, in transform
    raise MissingRequiredArgument('{0.name} is a required argument that is missing.'.format(param))
discord.ext.commands.errors.MissingRequiredArgument: channel is a required argument that is missing.
```
**Command**: `join` (no arguments or invalid argument)
**Possible solution**: Add a condition to the command function (if no arguments, use the same function as `summon` command (a.k.a. Join to the voice channel the user is in))

**Comment by MaT1g3R** [comment]
Fixed
